[package]
name = "jokester"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
icanhazdadjoke-sdk = "0.1.0"
mhteams = "0.1.0"
reqwest = "0.11.22"
tokio = { version = "1", features = ["full"] }
